apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jovisco-apps-de-tls
spec:
  secretName: jovisco-apps-de
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jovisco-apps.de
  dnsNames:
    - jovisco-apps.de
    - www.jovisco-apps.de
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - jovisco-apps.de
          - www.jovisco-apps.de
